# Generated by Django 5.2.5 on 2025-08-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
