# Generated by Django 5.2.5 on 2025-09-01 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalentry_confidence_journalentry_sentiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pages', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
